import 'package:flutter/material.dart';
import 'package:mvp_timer/constants/style.dart';
import 'package:mvp_timer/widgets/element_text.dart';

List<Race> raceList = [
  Races.all,
  Races.angel,
  Races.brute,
  Races.demon,
  Races.dragon,
  Races.fish,
  Races.formless,
  Races.human,
  Races.insect,
  Races.plant,
  Races.undead
];

List<MvPSize> sizeList = [
  MvPSizes.all,
  MvPSizes.small,
  MvPSizes.medium,
  MvPSizes.large,
];

List<Element> elementList = [
  Elements.all,
  Elements.dark,
  Elements.earth,
  Elements.fire,
  Elements.ghost,
  Elements.holy,
  Elements.neutral,
  Elements.poison,
  Elements.undead,
  Elements.water,
  Elements.wind
];

class Race {
  final String name;
  final Widget widget;

  Race({required this.name, required this.widget});
}

class Races {
  static Race all = Race(
      name: 'Todas',
      widget:
          ElementText(text: 'Todas', bgColor: neutralColor, textColor: darker));

  static Race formless = Race(
      name: 'Amorfo',
      widget: ElementText(
          text: 'Amorfo', bgColor: neutralColor, textColor: darker));
  static Race angel = Race(
      name: 'Anjo',
      widget:
          ElementText(text: 'Anjo', bgColor: neutralColor, textColor: darker));
  static Race brute = Race(
      name: 'Bruto',
      widget:
          ElementText(text: 'Bruto', bgColor: neutralColor, textColor: darker));
  static Race demon = Race(
      name: 'Demônio',
      widget: ElementText(
          text: 'Demônio', bgColor: neutralColor, textColor: darker));
  static Race dragon = Race(
      name: 'Dragão',
      widget: ElementText(
          text: 'Dragão', bgColor: neutralColor, textColor: darker));
  static Race human = Race(
      name: 'Humanoid',
      widget: ElementText(
          text: 'Humanoide', bgColor: neutralColor, textColor: darker));
  static Race insect = Race(
      name: 'Inseto',
      widget: ElementText(
          text: 'Inseto', bgColor: neutralColor, textColor: darker));
  static Race undead = Race(
      name: 'Morto-Vivo',
      widget: ElementText(
          text: 'Morto-Vivo', bgColor: neutralColor, textColor: darker));
  static Race fish = Race(
      name: 'Peixe',
      widget:
          ElementText(text: 'Peixe', bgColor: neutralColor, textColor: darker));
  static Race plant = Race(
      name: 'Planta',
      widget: ElementText(
          text: 'Planta', bgColor: neutralColor, textColor: darker));
}

class MvPSize {
  final String name;
  final Widget widget;

  MvPSize({required this.name, required this.widget});
}

class MvPSizes {
  static MvPSize all = MvPSize(
      name: 'Todos',
      widget:
          ElementText(text: 'Todos', bgColor: neutralColor, textColor: darker));

  static MvPSize small = MvPSize(
      name: 'Pequeno',
      widget: ElementText(
          text: 'Pequeno', bgColor: neutralColor, textColor: darker));
  static MvPSize medium = MvPSize(
      name: 'Médio',
      widget:
          ElementText(text: 'Médio', bgColor: neutralColor, textColor: darker));
  static MvPSize large = MvPSize(
      name: 'Grande',
      widget: ElementText(
          text: 'Grande', bgColor: neutralColor, textColor: darker));
}

class Element {
  final String name;
  final Widget widget;

  Element({required this.name, required this.widget});
}

class Elements {
  static Element all = Element(
      name: 'Todos',
      widget:
          ElementText(text: 'Todos', bgColor: neutralColor, textColor: darker));

  static Element neutral = Element(
      name: 'Neutro',
      widget: ElementText(
          text: 'Neutro', bgColor: neutralColor, textColor: darker));
  static Element water = Element(
      name: 'Água',
      widget:
          ElementText(text: 'Água', bgColor: waterColor, textColor: darker));
  static Element earth = Element(
      name: 'Terra',
      widget:
          ElementText(text: 'Terra', bgColor: earthColor, textColor: darker));
  static Element fire = Element(
      name: 'Fogo',
      widget: ElementText(text: 'Fogo', bgColor: fireColor, textColor: darker));
  static Element wind = Element(
      name: 'Vento',
      widget:
          ElementText(text: 'Vento', bgColor: windColor, textColor: darker));
  static Element poison = Element(
      name: 'Veneno',
      widget:
          ElementText(text: 'Veneno', bgColor: poisonColor, textColor: darker));
  static Element holy = Element(
      name: 'Sagrado',
      widget:
          ElementText(text: 'Sagrado', bgColor: holyColor, textColor: darker));
  static Element dark = Element(
      name: 'Sombrio',
      widget:
          ElementText(text: 'Sombrio', bgColor: darkColor, textColor: darker));
  static Element ghost = Element(
      name: 'Fantasma',
      widget: ElementText(
          text: 'Fantasma', bgColor: ghostColor, textColor: darker));
  static Element undead = Element(
      name: 'Maldito',
      widget:
          ElementText(text: 'Maldito', bgColor: undeadColor, textColor: light));
}

class ElementsDamage {
  final double neutral;
  final double water;
  final double earth;
  final double fire;
  final double wind;
  final double poison;
  final double holy;
  final double dark;
  final double ghost;
  final double undead;

  ElementsDamage(
      {required this.neutral,
      required this.water,
      required this.earth,
      required this.fire,
      required this.wind,
      required this.poison,
      required this.holy,
      required this.dark,
      required this.ghost,
      required this.undead});
}

class SpawnMap {
  final String name;
  final String mapId;
  final String mapUrl;
  final int respawn;
  SpawnMap(
      {required this.name,
      required this.mapId,
      required this.mapUrl,
      required this.respawn});
  SpawnMap.instanceMap(
      {required this.name,
      this.mapId = 'Instância',
      required this.mapUrl,
      required this.respawn});
}

class MvP {
  final int id;
  final String name;
  final int level;
  final Race race;
  final MvPSize size;
  final Element element;
  final double hp;
  final bool greenAura;
  final String gifUrl;
  final ElementsDamage elementsDamage;
  final List<SpawnMap> spawnMaps;

  MvP(
      {required this.id,
      required this.name,
      required this.level,
      required this.race,
      required this.size,
      required this.element,
      required this.hp,
      required this.greenAura,
      required this.gifUrl,
      required this.elementsDamage,
      required this.spawnMaps});
}

SpawnMap thMap = SpawnMap(
    name: 'Laboratório de Somatologia (Pesadelo)',
    mapId: 'lhz_dun_n',
    mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun_n',
    respawn: 120);

enum MvPGroup { TH, OW, IN }

List<MvP> allMvPs = [...thMvPs, ...owMvPs, ...inMvPs];

List<MvP> thMvPs = [
  MvP(
      id: 3241,
      name: 'Bioquímico Flamel',
      level: 186,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 14400000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3241.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
  MvP(
      id: 3245,
      name: 'Trovador Alphoccio',
      level: 186,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 10800000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3245.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
  MvP(
      id: 3246,
      name: 'Musa Trentini',
      level: 186,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 10800000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3246.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
  MvP(
      id: 3221,
      name: 'Arcebispa Margaretha',
      level: 187,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.holy,
      hp: 14400000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3221.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 0,
          fire: 0,
          wind: 0,
          poison: 0,
          holy: -100,
          dark: 200,
          ghost: 0,
          undead: 175),
      spawnMaps: [thMap]),
  MvP(
      id: 3223,
      name: 'Mecânico Harword',
      level: 187,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.water,
      hp: 18000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3223.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
  MvP(
      id: 3224,
      name: 'Arcana Kathryne',
      level: 187,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.ghost,
      hp: 10800000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3224.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 25,
          holy: 100,
          dark: 100,
          ghost: 200,
          undead: 100),
      spawnMaps: [thMap]),
  MvP(
      id: 3240,
      name: 'Guardião Real Randel',
      level: 188,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.holy,
      hp: 18000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3240.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 0,
          fire: 0,
          wind: 0,
          poison: 0,
          holy: -100,
          dark: 200,
          ghost: 0,
          undead: 175),
      spawnMaps: [thMap]),
  MvP(
      id: 3242,
      name: 'Feiticeira Celia',
      level: 188,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.ghost,
      hp: 16200000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3242.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 25,
          holy: 100,
          dark: 100,
          ghost: 200,
          undead: 100),
      spawnMaps: [thMap]),
  MvP(
      id: 3243,
      name: 'Shura Chen',
      level: 188,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.water,
      hp: 12600000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3243.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
  MvP(
      id: 3244,
      name: 'Renegada Gertie',
      level: 188,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.poison,
      hp: 14400000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3244.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [thMap]),
  MvP(
      id: 3220,
      name: 'Sicário Eremes',
      level: 189,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.poison,
      hp: 12600000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3220.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [thMap]),
  MvP(
      id: 3222,
      name: 'Sentinela Cecil',
      level: 189,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 12600000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3222.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
  MvP(
      id: 3225,
      name: 'Cavaleiro Rúnico Seyren',
      level: 189,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 14400000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3225.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [thMap]),
];

List<MvP> inMvPs = [
  MvP(
      id: 3810,
      name: 'Rei Poring',
      level: 35,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.neutral,
      hp: 140000,
      greenAura: false,
      gifUrl: 'https://static.divine-pride.net/images/mobs/png/3810.png',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Vila dos Porings',
            mapUrl: 'https://browiki.org/wiki/Vila_dos_Porings',
            respawn: 2400),
      ]),
  MvP(
      id: 3901,
      name: 'Orc Falso',
      level: 70,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 2110562,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1087.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 0,
          fire: 175,
          wind: 80,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Batalha dos Orcs',
            mapUrl: 'https://browiki.org/wiki/Batalha_dos_Orcs',
            respawn: 2400),
      ]),
  MvP(
      id: 1957,
      name: 'Entweihen Crothen',
      level: 90,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 2400500,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1957.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 25,
          earth: 25,
          fire: 25,
          wind: 25,
          poison: -25,
          holy: 200,
          dark: -100,
          ghost: 0,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Torre sem Fim',
            mapUrl: 'https://browiki.org/wiki/Torre_sem_Fim',
            respawn: 7003),
      ]),
  MvP(
      id: 2194,
      name: 'Polvo Gigante',
      level: 95,
      race: Races.fish,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 500000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2194.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 100,
          fire: 80,
          wind: 175,
          poison: 75,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Caverna do Polvo',
            mapUrl: 'https://browiki.org/wiki/Caverna_do_Polvo',
            respawn: 3),
      ]),
  MvP(
      id: 1929,
      name: 'Bafomé Selado',
      level: 98,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 4520500,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1929.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Altar do Selo',
            mapUrl: 'https://browiki.org/wiki/Altar_do_Selo',
            respawn: 12),
      ]),
  MvP(
      id: 1956,
      name: 'Naght Sieger',
      level: 99,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.ghost,
      hp: 5000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1956.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 25,
          holy: 100,
          dark: 100,
          ghost: 200,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Torre sem Fim',
            mapUrl: 'https://browiki.org/wiki/Torre_sem_Fim',
            respawn: 7003),
      ]),
  MvP(
      id: 2187,
      name: 'Celacanto Cruel',
      level: 100,
      race: Races.fish,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 2200000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2187.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 100,
          fire: 80,
          wind: 175,
          poison: 75,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Esgotos de Malangdo',
            mapUrl: 'https://browiki.org/wiki/Esgotos_de_Malangdo',
            respawn: 1),
      ]),
  MvP(
      id: 2188,
      name: 'Celacanto Sombrio',
      level: 100,
      race: Races.fish,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 2200000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2188.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 100,
          fire: 80,
          wind: 175,
          poison: 75,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Esgotos de Malangdo',
            mapUrl: 'https://browiki.org/wiki/Esgotos_de_Malangdo',
            respawn: 1),
      ]),
  MvP(
      id: 3628,
      name: 'Malícia',
      level: 100,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 2800000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3628.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Base Militar',
            mapUrl: 'https://browiki.org/wiki/Base_Militar',
            respawn: 2404),
      ]),
  MvP(
      id: 3450,
      name: 'Bijou',
      level: 115,
      race: Races.undead,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 10000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3450.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 50,
          fire: 200,
          wind: 100,
          poison: -100,
          holy: 200,
          dark: -100,
          ghost: 175,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Salão de Ymir',
            mapUrl: 'https://browiki.org/wiki/Salão_de_Ymir',
            respawn: 2400),
      ]),
  MvP(
      id: 2317,
      name: 'Bangungot',
      level: 115,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 1519517,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2317.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Hospital Abandonado',
            mapUrl: 'https://browiki.org/wiki/Hospital_Abandonado',
            respawn: 2400),
      ]),
  MvP(
      id: 2022,
      name: 'Sombra de Nidhogg',
      level: 117,
      race: Races.dragon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 3452000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2022.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 25,
          earth: 25,
          fire: 25,
          wind: 25,
          poison: -25,
          holy: 200,
          dark: -100,
          ghost: 0,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Ninho de Nidhogg',
            mapUrl: 'https://browiki.org/wiki/Ninho_de_Nidhogg',
            respawn: 3003),
      ]),
  MvP(
      id: 3621,
      name: 'Fofinho',
      level: 120,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 3500000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3621.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório Werner',
            mapUrl: 'https://browiki.org/wiki/Laboratório_Werner',
            respawn: 2404),
      ]),
  MvP(
      id: 3181,
      name: 'Capitão Ferlock',
      level: 130,
      race: Races.dragon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 3000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3181.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Invasão ao Aeroplano',
            mapUrl: 'https://browiki.org/wiki/Invasão_ao_Aeroplano',
            respawn: 2400),
      ]),
  MvP(
      id: 2131,
      name: 'Dragão Púrpura',
      level: 135,
      race: Races.dragon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 608920,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2131.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Invasão ao Aeroplano',
            mapUrl: 'https://browiki.org/wiki/Labirinto_da_Neblina',
            respawn: 150),
      ]),
  MvP(
      id: 2189,
      name: 'Celacanto Mutante',
      level: 155,
      race: Races.fish,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 5200000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2189.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 100,
          fire: 80,
          wind: 175,
          poison: 75,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Esgotos de Malangdo',
            mapUrl: 'https://browiki.org/wiki/Esgotos_de_Malangdo',
            respawn: 1),
      ]),
  MvP(
      id: 2190,
      name: 'Celacanto Violento',
      level: 155,
      race: Races.fish,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 5200000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2190.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 100,
          fire: 80,
          wind: 175,
          poison: 75,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Esgotos de Malangdo',
            mapUrl: 'https://browiki.org/wiki/Esgotos_de_Malangdo',
            respawn: 1),
      ]),
  MvP(
      id: 3073,
      name: 'Réquiem de Marfim',
      level: 140,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 19471800,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3073.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 125,
          earth: 100,
          fire: 175,
          wind: 100,
          poison: -75,
          holy: 200,
          dark: -75,
          ghost: 150,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Pesadelo Musical',
            mapUrl: 'https://browiki.org/wiki/Pesadelo_Musical',
            respawn: 2400),
      ]),
  MvP(
      id: 3124,
      name: 'Charleston 03',
      level: 145,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.neutral,
      hp: 23671401,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3124.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 0,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Charleston em Crise',
            mapUrl: 'https://browiki.org/wiki/Charleston_em_Crise',
            respawn: 2400),
      ]),
  MvP(
      id: 2475,
      name: 'Origem da Maldição',
      level: 150,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 1820000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2475.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Maldição de Glast Heim',
            mapUrl: 'https://browiki.org/wiki/Maldição_de_Glast_Heim',
            respawn: 2400),
      ]),
  MvP(
      id: 2476,
      name: 'Amdarais',
      level: 150,
      race: Races.undead,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 4290000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2476.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 50,
          fire: 200,
          wind: 100,
          poison: -100,
          holy: 200,
          dark: -100,
          ghost: 175,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Maldição de Glast Heim',
            mapUrl: 'https://browiki.org/wiki/Maldição_de_Glast_Heim',
            respawn: 2400),
      ]),
  MvP(
      id: 2319,
      name: 'Buwaya',
      level: 151,
      race: Races.dragon,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 4090365,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2319.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Caverna de Buwaya',
            mapUrl: 'https://browiki.org/wiki/Caverna_de_Buwaya',
            respawn: 2400),
      ]),
  MvP(
      id: 2942,
      name: 'Fanático das Trevas',
      level: 151,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 8256000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2942.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Torre do Demônio',
            mapUrl: 'https://browiki.org/wiki/Torre_do_Demônio',
            respawn: 2400),
      ]),
  MvP(
      id: 2529,
      name: 'Rainha Verme',
      level: 155,
      race: Races.insect,
      size: MvPSizes.large,
      element: Elements.poison,
      hp: 50000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2529.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Covil de Vermes',
            mapUrl: 'https://browiki.org/wiki/Covil_de_Vermes',
            respawn: 2400),
      ]),
  MvP(
      id: 2322,
      name: 'Bakonawa',
      level: 156,
      race: Races.dragon,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 3351884,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2322.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Lago de Bakonawa',
            mapUrl: 'https://browiki.org/wiki/Lago_de_Bakonawa',
            respawn: 2400),
      ]),
  MvP(
      id: 2999,
      name: 'Necromante de Morroc',
      level: 158,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.neutral,
      hp: 4000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2999.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 0,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Caverna de Mors',
            mapUrl: 'https://browiki.org/wiki/Caverna_de_Mors',
            respawn: 2400),
      ]),
  MvP(
      id: 3029,
      name: 'Ceifador Ankou',
      level: 159,
      race: Races.undead,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 50000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3029.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 50,
          fire: 200,
          wind: 100,
          poison: -100,
          holy: 200,
          dark: -100,
          ghost: 175,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Ilha Bios',
            mapUrl: 'https://browiki.org/wiki/Ilha_Bios',
            respawn: 2400),
      ]),
  MvP(
      id: 2564,
      name: 'Fenris Fenrir',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.ghost,
      hp: 20000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2564.gif',
      elementsDamage: ElementsDamage(
          neutral: 50,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 75,
          holy: 100,
          dark: 100,
          ghost: 150,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Torneio de Magia',
            mapUrl: 'https://browiki.org/wiki/Torneio_de_Magia',
            respawn: 2400),
      ]),
  MvP(
      id: 3473,
      name: 'Jack Wolf',
      level: 160,
      race: Races.undead,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 20000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3473.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 125,
          wind: 100,
          poison: -25,
          holy: 150,
          dark: -25,
          ghost: 100,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Sussurro Sombrio',
            mapUrl: 'https://browiki.org/wiki/Sussurro_Sombrio',
            respawn: 3003),
      ]),
  MvP(
      id: 1647,
      name: 'Algoz Eremes',
      level: 160,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.poison,
      hp: 4230000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1647.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 1649,
      name: 'Sumo Margaretha',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.holy,
      hp: 4800000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1649.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 0,
          fire: 0,
          wind: 0,
          poison: 0,
          holy: -100,
          dark: 200,
          ghost: 0,
          undead: 175),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 1650,
      name: 'Atiradora Cecil',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 4140000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1650.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 1651,
      name: 'Arquimaga Kathryne',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.ghost,
      hp: 4500000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1651.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 50,
          holy: 100,
          dark: 100,
          ghost: 175,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 1648,
      name: 'Mestre-ferreiro Harword',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.earth,
      hp: 6750000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1648.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -50,
          fire: 200,
          wind: 60,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 1646,
      name: 'Lorde Seyren',
      level: 160,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 4680000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1646.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2241,
      name: 'Cigana Trentini',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 3894278,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2241.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2240,
      name: 'Menestrel Alphoccio',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 3894278,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2240.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2237,
      name: 'Professora Celia',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.ghost,
      hp: 3847804,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2237.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 50,
          holy: 100,
          dark: 100,
          ghost: 175,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2236,
      name: 'Criador Flamel',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 4230000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2236.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2235,
      name: 'Paladino Randel',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.holy,
      hp: 6870000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2235.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 0,
          fire: 0,
          wind: 0,
          poison: 0,
          holy: -100,
          dark: 200,
          ghost: 0,
          undead: 175),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2239,
      name: 'Desordeira Gertie',
      level: 160,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.poison,
      hp: 4057279,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2239.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 2238,
      name: 'Mestre Chen',
      level: 160,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.water,
      hp: 4249350,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2238.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Laboratório de Wolfchev',
            mapUrl: 'https://browiki.org/wiki/Laboratório_de_Wolfchev',
            respawn: 3003),
      ]),
  MvP(
      id: 3190,
      name: 'Sara Irine',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.neutral,
      hp: 100000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3190.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 70,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Sarah vs Fenrir',
            mapUrl: 'https://browiki.org/wiki/Sarah_vs_Fenrir',
            respawn: 7003),
      ]),
  MvP(
      id: 2996,
      name: 'Celine Kimi',
      level: 160,
      race: Races.undead,
      size: MvPSizes.large,
      element: Elements.ghost,
      hp: 66666666,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2996.gif',
      elementsDamage: ElementsDamage(
          neutral: 70,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 125,
          undead: 100),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Fábrica do Terror',
            mapUrl: 'https://browiki.org/wiki/Fábrica_do_Terror',
            respawn: 2400),
      ]),
  MvP(
      id: 3254,
      name: 'T_W_O',
      level: 165,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 48000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3254.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Sala Final',
            mapUrl: 'https://browiki.org/wiki/Sala_Final',
            respawn: 2400),
      ]),
  MvP(
      id: 3097,
      name: 'Deus Morroc',
      level: 175,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 120000000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3097.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Templo do Demônio Rei',
            mapUrl: 'https://browiki.org/wiki/Templo_do_Demônio_Rei',
            respawn: 2400),
      ]),
  MvP(
      id: 3151,
      name: 'Origem da Escuridão',
      level: 180,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 18200000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3151.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Glast Heim Sombria',
            mapUrl: 'https://browiki.org/wiki/Glast_Heim_Sombria',
            respawn: 3003),
      ]),
  MvP(
      id: 3150,
      name: 'Amdarais Sombrio',
      level: 180,
      race: Races.undead,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 42900000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3150.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 50,
          fire: 200,
          wind: 100,
          poison: -100,
          holy: 200,
          dark: -100,
          ghost: 175,
          undead: 0),
      spawnMaps: [
        SpawnMap.instanceMap(
            name: 'Glast Heim Sombria',
            mapUrl: 'https://browiki.org/wiki/Glast_Heim_Sombria',
            respawn: 3003),
      ]),
];

List<MvP> owMvPs = [
  MvP(
      id: 3505,
      name: 'Gemaring',
      level: 25,
      race: Races.plant,
      size: MvPSizes.medium,
      element: Elements.earth,
      hp: 142480,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3505.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Ninho do Dragão',
            mapId: 'lasa_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lasa_dun01',
            respawn: 60)
      ]),
  MvP(
      id: 1087,
      name: 'Orc Herói',
      level: 50,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 362000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1087.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 0,
          fire: 175,
          wind: 80,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap(
            name: 'Arredores de Geffen (3)',
            mapId: 'gef_fild03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gef_fild03',
            respawn: 60)
      ]),
  MvP(
      id: 1147,
      name: 'Maya',
      level: 55,
      race: Races.insect,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 380000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1147.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -50,
          fire: 200,
          wind: 60,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Formigueiro Infernal (2)',
            mapId: 'anthell02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/anthell02',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço das Valquírias (1)',
            mapId: 'gld_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun03',
            respawn: 480),
        SpawnMap(
            name: 'Calabouço de Luina (1)',
            mapId: 'gld_dun02_2',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun02_2',
            respawn: 480),
      ]),
  MvP(
      id: 1190,
      name: 'Senhor dos Orcs',
      level: 55,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 552000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1190.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -50,
          fire: 200,
          wind: 60,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Arredores de Geffen (10)',
            mapId: 'gef_fild10',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gef_fild10',
            respawn: 60)
      ]),
  MvP(
      id: 1086,
      name: 'Besouro-Ladrão Dourado',
      level: 65,
      race: Races.insect,
      size: MvPSizes.large,
      element: Elements.fire,
      hp: 222750,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1086.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 175,
          earth: 90,
          fire: 0,
          wind: 100,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap(
            name: 'Esgotos de Prontera (4)',
            mapId: 'prt_sewb4',
            mapUrl: 'https://www.divine-pride.net/img/map/original/prt_sewb4',
            respawn: 60)
      ]),
  MvP(
      id: 1115,
      name: 'Eddga',
      level: 65,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.fire,
      hp: 947500,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1115.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 90,
          fire: 25,
          wind: 100,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 100,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Floresta de Payon (10)',
            mapId: 'pay_fild10',
            mapUrl: 'https://www.divine-pride.net/img/map/original/pay_fild10',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço do Bosque Celestial (1)',
            mapId: 'gld_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun01',
            respawn: 480),
        SpawnMap(
            name: 'Calabouço do Bosque Celestial (1)',
            mapId: 'gld_dun01_2',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun01_2',
            respawn: 480),
      ]),
  MvP(
      id: 1038,
      name: 'Osíris',
      level: 68,
      race: Races.undead,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 1175840,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1038.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 50,
          fire: 200,
          wind: 100,
          poison: -100,
          holy: 200,
          dark: -100,
          ghost: 175,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Pirâmide (4)',
            mapId: 'moc_pryd04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/moc_pryd04',
            respawn: 60)
      ]),
  MvP(
      id: 1511,
      name: 'Amon Ra',
      level: 69,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 1009000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1511.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Subsolo da Pirâmide (2)',
            mapId: 'moc_pryd06',
            mapUrl: 'https://www.divine-pride.net/img/map/original/moc_pryd06',
            respawn: 60)
      ]),
  MvP(
      id: 1159,
      name: 'Freeoni',
      level: 71,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.neutral,
      hp: 300000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1159.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 0,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Deserto de Sograt (17)',
            mapId: 'moc_fild17',
            mapUrl: 'https://www.divine-pride.net/img/map/original/moc_fild17',
            respawn: 60)
      ]),
  MvP(
      id: 1389,
      name: 'Drácula',
      level: 75,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 350000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1389.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 25,
          earth: 25,
          fire: 25,
          wind: 25,
          poison: -25,
          holy: 200,
          dark: -100,
          ghost: 0,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Calabouço de Geffen (1)',
            mapId: 'gef_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gef_dun01',
            respawn: 60)
      ]),
  MvP(
      id: 1046,
      name: 'Doppelganger',
      level: 77,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 380000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1046.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Calabouço de Geffen (2)',
            mapId: 'gef_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gef_dun02',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço de Luina (1)',
            mapId: 'gld_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun02',
            respawn: 480),
        SpawnMap(
            name: 'Calabouço de Britoniah (1)',
            mapId: 'gld_dun04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun04',
            respawn: 480),
      ]),
  MvP(
      id: 1059,
      name: 'Abelha-Rainha',
      level: 78,
      race: Races.insect,
      size: MvPSizes.small,
      element: Elements.wind,
      hp: 378000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1059.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Monte Mjolnir (4)',
            mapId: 'mjolnir_04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/mjolnir_04',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço de Luina (1)',
            mapId: 'gld_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun02',
            respawn: 480)
      ]),
  MvP(
      id: 1150,
      name: 'Flor do Luar',
      level: 79,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 324000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1150.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 70,
          fire: -25,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Caverna de Payon (4)',
            mapId: 'pay_dun04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/pay_dun04',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço do Bosque Celestial (1)',
            mapId: 'gld_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun01',
            respawn: 480)
      ]),
  MvP(
      id: 1688,
      name: 'Lady Tanee',
      level: 80,
      race: Races.plant,
      size: MvPSizes.large,
      element: Elements.wind,
      hp: 360000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1688.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 70,
          earth: 200,
          fire: 100,
          wind: -25,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Santuário Ancestral',
            mapId: 'ayo_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ayo_dun02',
            respawn: 420)
      ]),
  MvP(
      id: 1039,
      name: 'Bafomé',
      level: 81,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 668000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1039.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Labirinto da Floresta (3)',
            mapId: 'prt_maze03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/prt_maze03',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço das Valquírias (1)',
            mapId: 'gld_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun03',
            respawn: 480),
      ]),
  MvP(
      id: 1157,
      name: 'Faraó',
      level: 85,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 900000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1157.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Esfinge (5)',
            mapId: 'in_sphinx5',
            mapUrl: 'https://www.divine-pride.net/img/map/original/in_sphinx5',
            respawn: 60),
      ]),
  MvP(
      id: 1980,
      name: 'Kublin',
      level: 85,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.earth,
      hp: 633600,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1157.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 25,
          fire: 150,
          wind: 90,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 100,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Calabouço de Nithafjoll',
            mapId: 'schg_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/schg_dun01',
            respawn: 0),
        SpawnMap(
            name: 'Calabouço de Valfreyja',
            mapId: 'arug_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/arug_dun01',
            respawn: 0)
      ]),
  MvP(
      id: 1112,
      name: 'Drake',
      level: 91,
      race: Races.undead,
      size: MvPSizes.medium,
      element: Elements.undead,
      hp: 804500,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1112.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 125,
          wind: 100,
          poison: -25,
          holy: 150,
          dark: -25,
          ghost: 100,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Navio Fantasma (2)',
            mapId: 'treasure02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/treasure02',
            respawn: 60),
      ]),
  MvP(
      id: 1251,
      name: 'Cavaleiro da Tempestade',
      level: 92,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.wind,
      hp: 630500,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1251.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Fábrica de Brinquedos (2)',
            mapId: 'xmas_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/xmas_dun02',
            respawn: 67),
      ]),
  MvP(
      id: 2068,
      name: 'Boitatá',
      level: 93,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.fire,
      hp: 1283990,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2068.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 70,
          fire: -25,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Profundezas das Cataratas',
            mapId: 'bra_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/bra_dun02',
            respawn: 120),
      ]),
  MvP(
      id: 2156,
      name: 'Leak',
      level: 94,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 1266000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2156.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Vulcão Krakatau',
            mapId: 'dew_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/dew_dun01',
            respawn: 60),
      ]),
  MvP(
      id: 1373,
      name: 'Senhor dos Mortos',
      level: 94,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 1266000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1373.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Nifflheim',
            mapId: 'niflheim',
            mapUrl: 'https://www.divine-pride.net/img/map/original/niflheim',
            respawn: 133),
      ]),
  MvP(
      id: 1272,
      name: 'Senhor das Trevas',
      level: 96,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.undead,
      hp: 1190900,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1272.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 150,
          earth: 50,
          fire: 200,
          wind: 100,
          poison: -100,
          holy: 200,
          dark: -100,
          ghost: 175,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Cemitério de Glast Heim',
            mapId: 'gl_chyard',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gl_chyard',
            respawn: 60),
        SpawnMap(
            name: 'Cemitério de Glast Heim',
            mapId: 'gl_chyard_',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gl_chyard_',
            respawn: 60),
        SpawnMap(
            name: 'Calabouço de Britoniah (1)',
            mapId: 'gld_dun04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun04',
            respawn: 480),
        SpawnMap(
            name: 'Calabouço de Britoniah (1)',
            mapId: 'gld_dun04_2',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun04_2',
            respawn: 480),
      ]),
  MvP(
      id: 1885,
      name: 'Gorynych',
      level: 97,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 1120500,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1885.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Floresta Encantada (3)',
            mapId: 'mosk_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/mosk_dun03',
            respawn: 60),
      ]),
  MvP(
      id: 1630,
      name: 'Lady Branca',
      level: 97,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.wind,
      hp: 720500,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1630.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 70,
          earth: 200,
          fire: 100,
          wind: -25,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Suei Long Gon',
            mapId: 'lou_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lou_dun03',
            respawn: 116),
      ]),
  MvP(
      id: 1252,
      name: 'Hatii',
      level: 98,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 1275500,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1252.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Arredores de Lutie',
            mapId: 'xmas_fild01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/xmas_fild01',
            respawn: 60),
      ]),
  MvP(
      id: 1779,
      name: 'Ktullanux',
      level: 98,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 2626000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1779.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Caverna de Gelo (3)',
            mapId: 'ice_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ice_dun03',
            respawn: 60),
      ]),
  MvP(
      id: 1708,
      name: 'Memória de Thanatos',
      level: 99,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.ghost,
      hp: 1445660,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1708.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 25,
          holy: 100,
          dark: 100,
          ghost: 200,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Topo da Torre de Thanatos',
            mapId: 'thana_boss',
            mapUrl: 'https://www.divine-pride.net/img/map/original/thana_boss',
            respawn: 60),
      ]),
  MvP(
      id: 2442,
      name: 'Superaprendiz',
      level: 99,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 268800,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2442.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Calabouço de Luina (1)',
            mapId: 'teg_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/teg_dun02',
            respawn: 180),
      ]),
  MvP(
      id: 2441,
      name: 'Aprendiz',
      level: 99,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 265203,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2441.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Calabouço das Valquírias (1)',
            mapId: 'teg_dun01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/teg_dun01',
            respawn: 180),
      ]),
  MvP(
      id: 1623,
      name: 'RSX-0806',
      level: 100,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.neutral,
      hp: 1001000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1623.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 0,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Calabouço da Mina (2)',
            mapId: 'ein_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ein_dun02',
            respawn: 125),
      ]),
  MvP(
      id: 1492,
      name: 'Samurai Encarnado',
      level: 100,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 901000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1492.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Templo Subterrâneo',
            mapId: 'ama_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ama_dun03',
            respawn: 91),
      ]),
  MvP(
      id: 1418,
      name: 'Serpente Suprema',
      level: 105,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.ghost,
      hp: 1101000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1418.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 50,
          holy: 100,
          dark: 100,
          ghost: 175,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Terra das Fadas',
            mapId: 'gon_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gon_dun03',
            respawn: 94),
      ]),
  MvP(
      id: 1583,
      name: 'Tao Gunka',
      level: 110,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.neutral,
      hp: 1252000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1583.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 0,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Karu, a Caverna do Oeste',
            mapId: 'beach_dun',
            mapUrl: 'https://www.divine-pride.net/img/map/original/beach_dun',
            respawn: 300),
      ]),
  MvP(
      id: 1312,
      name: 'General Tartaruga',
      level: 110,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 1442000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1312.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 0,
          fire: 175,
          wind: 80,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap(
            name: 'Palácio Tartaruga',
            mapId: 'tur_dun04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/tur_dun04',
            respawn: 60),
      ]),
  MvP(
      id: 3633,
      name: 'Quimera Venenosa',
      level: 110,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.poison,
      hp: 2800000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3633.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório Werner',
            mapId: 'slabw01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/slabw01',
            respawn: 60)
      ]),
  MvP(
      id: 1785,
      name: 'Atroce',
      level: 113,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 1502000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1785.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Planície de Ida',
            mapId: 'ra_fild03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ra_fild03',
            respawn: 180),
        SpawnMap(
            name: 'Pradaria Audhumbla',
            mapId: 'ra_fild04',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ra_fild04',
            respawn: 300),
        SpawnMap(
            name: 'Arredores de Veins (1)',
            mapId: 've_fild01',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ve_fild01',
            respawn: 180),
        SpawnMap(
            name: 'Arredores de Veins (2)',
            mapId: 've_fild02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ve_fild02',
            respawn: 360),
        SpawnMap(
            name: 'Calabouço das Valquírias (1)',
            mapId: 'gld_dun03_2',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld_dun03_2',
            respawn: 480)
      ]),
  MvP(
      id: 3758,
      name: 'Ilusão do Luar',
      level: 118,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 4287803,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3758.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 70,
          fire: -25,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Ilusão da Lua',
            mapId: 'pay_d03_i',
            mapUrl: 'https://www.divine-pride.net/img/map/original/pay_d03_i',
            respawn: 0)
      ]),
  MvP(
      id: 2202,
      name: 'Kraken',
      level: 124,
      race: Races.fish,
      size: MvPSizes.large,
      element: Elements.water,
      hp: 5602800,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2202.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: -50,
          earth: 100,
          fire: 60,
          wind: 200,
          poison: 25,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Túnel Submarino (5)',
            mapId: 'iz_dun05',
            mapUrl: 'https://www.divine-pride.net/img/map/original/iz_dun05',
            respawn: 140)
      ]),
  MvP(
      id: 1734,
      name: 'Kiel-D-01',
      level: 125,
      race: Races.formless,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 2502000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1734.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Fábrica de Robôs (2)',
            mapId: 'kh_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/kh_dun02',
            respawn: 120)
      ]),
  MvP(
      id: 1685,
      name: 'Vesper',
      level: 128,
      race: Races.brute,
      size: MvPSizes.large,
      element: Elements.holy,
      hp: 3802000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1685.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 50,
          holy: -25,
          dark: 150,
          ghost: 50,
          undead: 125),
      spawnMaps: [
        SpawnMap(
            name: 'Centro de Juperos',
            mapId: 'jupe_core',
            mapUrl: 'https://www.divine-pride.net/img/map/original/jupe_core',
            respawn: 120)
      ]),
  MvP(
      id: 1719,
      name: 'Detardeurus',
      level: 135,
      race: Races.dragon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 6005000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1719.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Caverna Subterrânea do Lago do Abismo (3)',
            mapId: 'abyss_03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/abyss_03',
            respawn: 180)
      ]),
  MvP(
      id: 1871,
      name: 'Bispo Decadente',
      level: 138,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.dark,
      hp: 5655000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1871.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 25,
          holy: 150,
          dark: -25,
          ghost: 50,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Monastério (2)',
            mapId: 'abbey02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/abbey02',
            respawn: 120)
      ]),
  MvP(
      id: 1768,
      name: 'Pesar Noturno',
      level: 139,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.ghost,
      hp: 3005000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1768.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 50,
          holy: 100,
          dark: 100,
          ghost: 175,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Santuário de Freya (5)',
            mapId: 'ra_san05',
            mapUrl: 'https://www.divine-pride.net/img/map/original/ra_san05',
            respawn: 300)
      ]),
  MvP(
      id: 2087,
      name: 'Rainha Scaraba',
      level: 140,
      race: Races.insect,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 2441600,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2087.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Caverna Scaraba',
            mapId: 'dic_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/dic_dun02',
            respawn: 120)
      ]),
  MvP(
      id: 2165,
      name: 'Rainha Scaraba Dourada',
      level: 140,
      race: Races.insect,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 6441600,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2165.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Caverna Scaraba',
            mapId: 'dic_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/dic_dun03',
            respawn: 120)
      ]),
  MvP(
      id: 2362,
      name: 'Amon Ra do Pesadelo',
      level: 145,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 2515784,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2362.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Subsolo da Pirâmide (2) - Pesadelo',
            mapId: 'moc_prydn2',
            mapUrl: 'https://www.divine-pride.net/img/map/original/moc_prydn2',
            respawn: 60)
      ]),
  MvP(
      id: 1658,
      name: 'Espadachim Egnigem',
      level: 141,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 2910088,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1658.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 175,
          earth: 90,
          fire: 0,
          wind: 100,
          poison: 125,
          holy: 100,
          dark: 100,
          ghost: 75,
          undead: 75),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (2)',
            mapId: 'lhz_dun02',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun02',
            respawn: 120)
      ]),
  MvP(
      id: 1751,
      name: 'Valquíria Randgris',
      level: 141,
      race: Races.angel,
      size: MvPSizes.large,
      element: Elements.holy,
      hp: 3205000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1751.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 0,
          fire: 0,
          wind: 0,
          poison: 0,
          holy: -100,
          dark: 200,
          ghost: 0,
          undead: 175),
      spawnMaps: [
        SpawnMap(
            name: 'Templo de Odin (3)',
            mapId: 'odin_tem03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/odin_tem03',
            respawn: 480)
      ]),
  MvP(
      id: 2249,
      name: 'Pyuriel Furiosa',
      level: 141,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 2205000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2249.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Caminho do Guerreiro',
            mapId: 'gld2_prt',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld2_prt',
            respawn: 480)
      ]),
  MvP(
      id: 2253,
      name: 'General Daehyun',
      level: 142,
      race: Races.human,
      size: MvPSizes.large,
      element: Elements.earth,
      hp: 2500148,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2253.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -25,
          fire: 200,
          wind: 70,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 50,
          undead: 50),
      spawnMaps: [
        SpawnMap(
            name: 'Ventos Ancestrais',
            mapId: 'gld2_pay',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld2_pay',
            respawn: 480)
      ]),
  MvP(
      id: 2255,
      name: 'Guardião Morto Kades',
      level: 143,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 2505000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2255.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Colina dos Mortos',
            mapId: 'gld2_gef',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld2_gef',
            respawn: 480)
      ]),
  MvP(
      id: 2251,
      name: 'Gioia',
      level: 146,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.wind,
      hp: 2507989,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2251.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Lágrimas do Herói',
            mapId: 'gld2_ald',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gld2_ald',
            respawn: 480)
      ]),
  MvP(
      id: 1832,
      name: 'Ifrit',
      level: 146,
      race: Races.formless,
      size: MvPSizes.large,
      element: Elements.fire,
      hp: 6935000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1832.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Vulcão de Thor (3)',
            mapId: 'thor_v03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/thor_v03',
            respawn: 660)
      ]),
  MvP(
      id: 1874,
      name: 'Belzebu',
      level: 147,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.ghost,
      hp: 4805000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1874.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 25,
          holy: 100,
          dark: 100,
          ghost: 200,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Monastério (3)',
            mapId: 'abbey03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/abbey03',
            respawn: 720)
      ]),
  MvP(
      id: 2483,
      name: 'Bafomé Amaldiçoado',
      level: 154,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 4008000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/2483.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 50,
          earth: 50,
          fire: 50,
          wind: 50,
          poison: 0,
          holy: 175,
          dark: -50,
          ghost: 25,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Castelo Amaldiçoado',
            mapId: 'gl_cas02_',
            mapUrl: 'https://www.divine-pride.net/img/map/original/gl_cas02_',
            respawn: 120)
      ]),
  MvP(
      id: 1917,
      name: 'Morroc Ferido',
      level: 151,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.dark,
      hp: 5000000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1917.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 25,
          earth: 25,
          fire: 25,
          wind: 25,
          poison: -25,
          holy: 200,
          dark: -100,
          ghost: 0,
          undead: 0),
      spawnMaps: [
        SpawnMap(
            name: 'Deserto de Sograt (22)',
            mapId: 'moc_fild22',
            mapUrl: 'https://www.divine-pride.net/img/map/original/moc_fild22',
            respawn: 720)
      ]),
  MvP(
      id: 1647,
      name: 'Algoz Eremes',
      level: 160,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.poison,
      hp: 4230000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1647.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 75,
          earth: 75,
          fire: 75,
          wind: 75,
          poison: 0,
          holy: 125,
          dark: -25,
          ghost: 25,
          undead: -25),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (3)',
            mapId: 'lhz_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun03',
            respawn: 0)
      ]),
  MvP(
      id: 1649,
      name: 'Sumo Margaretha',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.holy,
      hp: 4800000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1649.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 0,
          earth: 0,
          fire: 0,
          wind: 0,
          poison: 0,
          holy: -100,
          dark: 200,
          ghost: 0,
          undead: 175),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (3)',
            mapId: 'lhz_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun03',
            respawn: 0)
      ]),
  MvP(
      id: 1650,
      name: 'Atiradora Cecil',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.wind,
      hp: 4140000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1650.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 60,
          earth: 200,
          fire: 100,
          wind: -50,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (3)',
            mapId: 'lhz_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun03',
            respawn: 0)
      ]),
  MvP(
      id: 1651,
      name: 'Arquimaga Kathryne',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.ghost,
      hp: 4500000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1651.gif',
      elementsDamage: ElementsDamage(
          neutral: 0,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 50,
          holy: 100,
          dark: 100,
          ghost: 175,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (3)',
            mapId: 'lhz_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun03',
            respawn: 0)
      ]),
  MvP(
      id: 1648,
      name: 'Mestre-ferreiro Harword',
      level: 160,
      race: Races.human,
      size: MvPSizes.medium,
      element: Elements.earth,
      hp: 6750000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1648.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: -50,
          fire: 200,
          wind: 60,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (3)',
            mapId: 'lhz_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun03',
            respawn: 0)
      ]),
  MvP(
      id: 1646,
      name: 'Lorde Seyren',
      level: 160,
      race: Races.demon,
      size: MvPSizes.medium,
      element: Elements.fire,
      hp: 4680000,
      greenAura: false,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/1646.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 200,
          earth: 60,
          fire: -50,
          wind: 100,
          poison: 75,
          holy: 75,
          dark: 75,
          ghost: 25,
          undead: 25),
      spawnMaps: [
        SpawnMap(
            name: 'Laboratório de Somatologia (3)',
            mapId: 'lhz_dun03',
            mapUrl: 'https://www.divine-pride.net/img/map/original/lhz_dun03',
            respawn: 0)
      ]),
  MvP(
      id: 3074,
      name: 'Vigia do Tempo',
      level: 170,
      race: Races.demon,
      size: MvPSizes.large,
      element: Elements.neutral,
      hp: 25000000,
      greenAura: true,
      gifUrl: 'https://static.ragnaplace.com/db/npc/gif/3074.gif',
      elementsDamage: ElementsDamage(
          neutral: 100,
          water: 100,
          earth: 100,
          fire: 100,
          wind: 100,
          poison: 100,
          holy: 100,
          dark: 100,
          ghost: 0,
          undead: 100),
      spawnMaps: [
        SpawnMap(
            name: 'Torre Distorcida (3)',
            mapId: 'c_tower3_',
            mapUrl: 'https://www.divine-pride.net/img/map/original/c_tower3_',
            respawn: 120)
      ]),
];
